### ISSUE TITLE
export/copy quadtree from one store to another store ...

### ISSUE THREAD

**Issue by stefanmaierhofer** [aardvark-platform/aardvark.geometry.quadtree#1]
... similar to https://github.com/aardvark-platform/aardvark.algodat/blob/d7486d3411d8ee04aa37087126dd58ee6eaa16e0/src/Aardvark.Geometry.PointSet/Octrees/Export.cs#L62

**Comment by stefanmaierhofer** [comment]
implemented `Quadtree.Export`

```f#
/// Export quadtree with given id from source to target.
    let Export 
        (source : SerializationOptions)
        (target : SerializationOptions)
        (progress : Option<int * int -> unit>)
        (ct : CancellationToken)
        (id : Guid)
        : unit = ...
```

An optional `progress` callback is called after each exported quadtree node with `(<exportedNodesSoFar>, <totalNodeCount>)`.

Important: if `Some progress` is provided, then the source quadtree is iterated twice (once for counting the total number of nodes, and once for copying each node), which may add some overhead for large out-of-core quadtrees **before** progress reporting starts.
If `None` is provided for `progress`, then the first iteration for counting is skipped and no overhead is incurred.

**Comment by stefanmaierhofer** [comment]
@jnothbauer please test and close if ok!

**Comment by jnothbauer** [comment]
Sorry for the delay, we had to restructure our model first.
Tested the export, works as expected
