### ISSUE TITLE
fix Query.IntersectsCell'

### ISSUE THREAD

**Issue by stefanmaierhofer** [aardvark-platform/aardvark.geometry.quadtree#2]
currently does not work (after rewrite of core quadtree data structure)

**Comment by stefanmaierhofer** [comment]
hopefully fixed the problem

see https://github.com/aardvark-platform/aardvark.geometry.quadtree/commit/964cde57fac992dde504173d6e7aa712acb09019 and [Aardvark.Geometry.Quadtree 0.2.1](https://www.nuget.org/packages/Aardvark.Geometry.Quadtree/0.2.1)

@cpunz please test, and if it works we can rename `IntersectsCell'` to `IntersectsCell` and remove the old implementation ...

**Comment by stefanmaierhofer** [comment]
feedback from @cpunz:
- works correctly 👍
- very fast in the in-memory case 👍
- but very slow in the out-of-core case 👎

**Comment by stefanmaierhofer** [comment]
After some investigation it turns out, that in the out-of-core case the performance is as expected for a **single call** to `IntersectsCell'`. Unfortunately, for repeated calls, out-of-core nodes are deserialized all over again, which results in poor performance.

**Comment by stefanmaierhofer** [comment]
[fix] added per-context cache for OutOfCoreNode loads to SerializationOptions, which boosts performance to almost in-memory levels (apart from initial deserialization), see https://github.com/aardvark-platform/aardvark.geometry.quadtree/commit/82cecbbdb367d14516a8b00238ad9c12b9780fc9

**Comment by stefanmaierhofer** [comment]
[finally] replaced old `Query.IntersectsCell` implementation with new `Query.IntersectsCell'` implementation

`Query.IntersectsCell'` still exists as an alias with `[<Obsolete>]` attribute (to not break existing code) and will be removed in the future, see https://github.com/aardvark-platform/aardvark.geometry.quadtree/commit/6722b33d76b84072a14463e04a2bea57596c9e3d

**Comment by stefanmaierhofer** [comment]
published https://www.nuget.org/packages/Aardvark.Geometry.Quadtree/0.2.2

**Comment by stefanmaierhofer** [comment]
@cpunz please test if out-of-core is now fast enough and replace all calls to `Query.IntersectsCell'` with `Query.IntersectsCell`
if everything's fine, please close this issue :-)

**Comment by cpunz** [comment]
Looks really good now!!
