### ISSUE TITLE
loading of old quadtree format is slow

### ISSUE THREAD

**Issue by stefanmaierhofer** [aardvark-platform/aardvark.geometry.quadtree#3]
Quadtree.Load or Quadtree.Exists takes a really long time for quadtrees stored in old format (e.g. 0.1.16)

It seems like the full tree is loaded from disk (or worse?) and out-of-core management is circumvented.

**Comment by stefanmaierhofer** [comment]
ok, when the old format is encountered, then it is converted to the new format on-the-fly (but not stored in the new format)
... and the ExactBoundingBox property of the new format is computed recursively from child nodes (which results in loading the full tree from storage, even if only the root node is needed)

**Comment by stefanmaierhofer** [comment]
published [Aardvark.Geometry.Quadtree 0.2.5](https://www.nuget.org/packages/Aardvark.Geometry.Quadtree/0.2.5)

**Comment by madorjan** [comment]
Query.All is now significantly slower than before. Quadtree.get finished instantly.

0.2.4: 
Quadtree.get 104.558s
Query.All 7.893s

0.2.5: 
Quadtree.get 0.069s
Query.All 115.011s

**Comment by stefanmaierhofer** [comment]
well, the data has to be loaded at some point, version 0.2.5 basically traded this time from `get` to `Query.All`, but we can't enumerate **all** samples without loading **all** data ;-)

| | get | all | total |
|---|---|---|---|
|0.2.4|105s|8s|**113s**|
|0.2.5|0s|115s|**115s**|

are your timings for the same data as in the previous 0.1.16 test (86s)?

![image](https://user-images.githubusercontent.com/2177683/106123783-a8b02880-615a-11eb-9841-56859627632f.png)

**Comment by madorjan** [comment]
No, timings are based on the store pushed to onedrive with quadtree-id 756bb95e-b6ac-4afa-9042-46c1c08ee0b0

**Comment by stefanmaierhofer** [comment]
ok, then what was the time in 0.1.16 for `Query.All` for that store?

**Comment by madorjan** [comment]
![grafik](https://user-images.githubusercontent.com/14292536/106126549-c8951b80-615d-11eb-9f98-2d212df733f9.png)

**Comment by stefanmaierhofer** [comment]
I can reproduce this locally now, but I currently have no idea where the difference comes from, because both versions basically use the same deserialization code -> investigating ... :-)

**Comment by stefanmaierhofer** [comment]
I have reduced the test to the bare minimum now - decoding all the nodes myself (to ensure no unexpected code is running) and simply traversing the full tree 

-> the exact same code takes about twice as long in 0.2.5 compared to 0.1.16, all package versions are the same (except SimpleStore for which I timed all operations and makes no difference)

-> performance profiler in vs unfortunately is broken in my netcore setup

-> giving up for now

**Comment by stefanmaierhofer** [comment]
... found 1 remaining difference -> sanity check of parameters when constructing nodes/datamappings -> investigating ...

**Comment by stefanmaierhofer** [comment]
seems like a few calls to `sprintf` in argument checks were more than 4x as expensive as the actual work (including reading and parsing ~1GB of data from disk) 😱

**Comment by stefanmaierhofer** [comment]
published [Aardvark.Geometry.Quadtree 0.2.6](https://www.nuget.org/packages/Aardvark.Geometry.Quadtree/0.2.6)

@madorjan please test again 😃!

**Comment by madorjan** [comment]
0.2.6 ... 30s
0.1.16 ... 62s

Query.All with 0.2.6 is even faster than with 0.1.16 now. thanks! 👍
