### ISSUE TITLE
add new node type with custom id (reference/"softlink") 

### ISSUE THREAD

**Issue by stefanmaierhofer** [aardvark-platform/aardvark.geometry.quadtree#4]
Add a new quadtree node type, which
- references another existing node
- takes a custom (user-specified) id

Currently the main use case would be to enable certain automated integration test scenarios which expect quadtrees with specific IDs.

**Comment by stefanmaierhofer** [comment]
```f#
let a : QNodeRef = ... 

// create a node with custom id, which links/forwards to existing node
let customid = "810c9ed9-ad01-49c5-9fa4-028f5ebb3406" |> Guid.Parse
let b : QNodeRef = Quadtree.Link customid a
```

**Comment by stefanmaierhofer** [comment]
available in `Aardvark.Geometry.Quadtree.0.2.7.nupkg`

**Comment by madorjan** [comment]
link works, thanks!
